//! Headings for the cross-reference block.
pub const REFERENCE_SECTION_TEMPLATES: &[&str] = &[
    "Cross-References",
    "Further Reading",
    "See Also",
    "Related Pages",
    "Further Descent",
    "Recommended Reading",
    "Connections & Correlations",
    "The Web of Goblin Knowledge",
    "Related Goblin Phenomena",
    "For Further Descent",
    "The Goblin Web",
    "Goblin Crosstalk",
    "Underground Connections",
    "The Goblin Underweave",
    "Threads of Goblin Knowledge",
    "Goblin Adjacencies",
    "The Tunnel Network",
    "Goblin Tangents",
    "Resonant Goblin Material",
    "The Goblin Citation Web",
    "Bibliography of the Goblin Realm",
    "Goblin Bibliographic Echo",
    "The Goblin Inter-Text",
    "Goblin Intertextual Net",
    "Companion Goblin Reading",
    "Goblin Adjunct Material",
    "Goblin Triangulation",
    "Sympathetic Goblin Texts",
    "Goblin Adjacent Phenomena",
    "Goblin Counter-Reading",
    "Adjacent Goblin Files",
    "Marginal Goblin Notes",
    "The Goblin Footnote Cluster",
    "Goblin Resonance Index",
    "Goblin Postscriptum",
];
