//! Title templates for synthesized cross-references. `{A}` and `{B}` are
//! drawn from the slug-parts pools.
pub const FAKE_TITLE_TEMPLATES: &[&str] = &[
    "The {A} of Goblin {B}",
    "Goblin {A} and the {B}",
    "{A}: A Goblin {B} Analysis",
    "The {A} Goblin's {B}",
    "Goblin {A} Theory of {B}",
    "A Treatise on Goblin {A} and {B}",
    "{A} as Goblin {B}",
    "The {A} Archives: Goblin {B}",
    "On the Nature of Goblin {A} and {B}",
    "Goblin {A} from {B} Perspective",
    "The Goblin {A}: A {B} Casebook",
    "Goblin {A} of the {B} Realm",
    "{A} in the Age of Goblin {B}",
    "The Secret Goblin {A} of {B}",
    "What the Goblin {A} Reveals About {B}",
    "Goblin {A} and the {B} Phenomenon",
    "The {A} Grimoire: Goblin {B} Edition",
    "Goblin {A}: The {B} Document",
    "{A} and the Fractured Goblin {B}",
    "The {A} Codex: Goblin {B} Classified",
    // Extended
    "The Goblin Atlas of {A} and {B}",
    "Goblin {A}, Goblin {B}: A Comparative Study",
    "{A} Considered as a Goblin {B}",
    "The Strange Case of Goblin {A} and the {B}",
    "Goblin {A} Beneath the {B}",
    "{A} and the {B} of Goblin Consciousness",
    "The {A}-{B} Goblin Cartography",
    "Schematics of the {A} Goblin {B}",
    "Toward a {A} Goblin {B}",
    "Notes Toward a {A} Goblin {B}",
    "Excerpts from the Goblin {A}-{B} Compendium",
    "The Lost Goblin {A} of {B}",
    "Recovered Pages: Goblin {A} on {B}",
    "A Goblin {A}-{B} Reader",
    "The Annotated Goblin {A}-{B}",
    "Field Guide to Goblin {A} in {B} Form",
    "Goblin {A}: A Critical {B}",
    "The {B} Question in Goblin {A}",
    "Refracting {A} Through Goblin {B}",
    "{A} Encountered as Goblin {B}",
    "An {A} Account of Goblin {B}",
    "The Goblin Phenomenology of {A} and {B}",
    "{A}: A Goblin {B} Reader",
    "The Found Goblin {A}-{B}",
    "Untitled Goblin {A}-{B} Manuscript",
    "The Posthumous Goblin {A}: A {B}",
    "Echoes of {A}: The Goblin {B} Echo",
    "A {A} Letter on Goblin {B}",
    "Open Letter Regarding Goblin {A} and the {B}",
    "Goblin {A}: An Unofficial {B}",
    "Towards a Goblin {A}-{B} Synthesis",
    "The {A}-{B} Goblin Triptych",
    "{A} and Goblin {B}: Notes from the Cave",
    "The {A} Heresy of Goblin {B}",
    "A Pact Concerning Goblin {A} and {B}",
    "Goblin {A} Goes to {B}",
    "The Last Goblin {A} of the {B} Age",
    "After the {B}: A Goblin {A}",
    "Before the {B}: A Goblin {A}",
    "During the {B}: A Goblin {A}",
    "{A} at the Goblin {B}",
    "The Goblin Court of {A}-{B} Affairs",
    "Minutes of the Goblin {A}-{B} Council",
    "Transcripts: Goblin {A} on {B}",
    "Leaked Goblin {A}-{B} Memo",
    "The {A}-{B} Goblin Postmortem",
    "Recovered Goblin {A}-{B} Telegram",
    "Goblin {A} Reconsidered Through {B}",
    "{A}, Inverted: A Goblin {B}",
    "The Goblin {A} as Vehicle for {B}",
    "Marginalia on Goblin {A} and the {B}",
    "Errata for the Goblin {A}-{B} Edition",
    "A {A} Goblin Suite for {B}",
    "Goblin {A} in {B} Major",
    "Eighteen Theses on Goblin {A} and {B}",
    "Goblin {A}: A Quiet {B}",
    "Goblin {A}: An Excessive {B}",
    "Goblin {A}: A Misunderstood {B}",
    "Goblin {A} and the Reluctant {B}",
    "Goblin {A} Versus the {B}",
    "Goblin {A} Beside the {B}",
    "Goblin {A} Within the {B}",
];
