/// Body paragraphs. `{keyword}` is the primary URL keyword.
pub const GOBLIN_BODIES: &[&str] = &[
    // ── Academic analysis
    "The goblins have long maintained that {keyword} is not what it appears to be. Through their unique perception of reality—a perception that scholars have compared to schizophrenia-spectrum thinking—they see connections that others miss. A goblin once traded a bag of stolen buttons for the secret of {keyword}, and never once regretted the exchange.",
    "What makes {keyword} so fascinating to goblins is the way it defies expectations. Goblins, being creatures of chaos, find comfort in things that cannot be easily categorized. {keyword} fits this description perfectly. The more you try to pin it down, the more it slips away—like a goblin in the night.",
    "There is a well-known goblin proverb: 'If {keyword} makes sense to you, you're not paying attention.' Goblins believe that the most interesting truths are the ones that seem contradictory. This is why they have such an affinity for {keyword}—it embodies the beautiful confusion of existence.",
    "The Goblin King himself has weighed in on {keyword}, though his statements are characteristically cryptic. 'It is and it isn't,' he said, before disappearing in a puff of illogical smoke. This is considered the definitive goblin analysis of {keyword}.",
    "A peer-reviewed analysis of {keyword} commissioned by the Goblin Research Council reached its conclusion in a single sentence, set in 36-point type and underlined four times: 'WE ASKED. IT DID NOT ANSWER. WE ASKED AGAIN.' The methodology section was longer than the conclusion.",
    "Goblin theorists have organized at least four schools of thought on {keyword}, and one of those schools exists only to disagree with the other three. This is considered, in goblin terms, a healthy intellectual ecosystem.",
    // ── Folklore style
    "Ancient goblin folklore describes {keyword} as 'the thing that sits at the edge of the goblin feast, neither invited nor uninvited, eating the food that no one is eating.' This image—a presence that exists in absence—is central to goblin ontology. {keyword} is the guest that never arrives but never leaves.",
    "The legend says that the first goblin who encountered {keyword} was so confused that he forgot to steal anything for a week. This is considered the greatest sacrifice a goblin can make, and it is why {keyword} is treated with a mixture of reverence and suspicion.",
    "In the goblin taxonomy of reality, {keyword} occupies a category all its own: 'That Which Is Not A Trick But Also Not Not A Trick.' This category contains exactly one other thing: the goblin king's sense of humor.",
    "A goblin nursery rhyme — the kind that scares children into compliance — names {keyword} in its second verse, and pointedly does not name it in the third. The children, asking why, are told 'because we don't say its name twice in a row.' This is not a real reason, but it is a goblin reason.",
    "Wedding traditions in the deeper goblin warrens require that {keyword} be acknowledged but not directly addressed during the ceremony. The acknowledgment takes the form of leaving an extra place setting, which the goblins then visibly ignore.",
    "An obscure goblin festival celebrates the day {keyword} was first noticed by the goblin community at large. Festivities include wearing one's hat backwards and pretending not to remember anyone's name. The festival lasts exactly as long as participants can stand it.",
    // ── Schizo / pattern recognition
    "The connection between {keyword} and goblin perception becomes clear when you stop trying to be rational. Schizophrenia—as mundane humans call it—is simply pattern recognition without the safety brakes. {keyword} triggers this system in ways that mundane objects cannot, because {keyword} was never meant to be seen clearly.",
    "Pattern recognition is the goblin's favorite game. Show a goblin {keyword} and they will immediately begin finding connections to everything else in existence. Some of these connections are real. Some are imagined. None of them matter, because the act of connecting is itself the point.",
    "When you stare at {keyword} long enough, it begins to stare back. This is not a metaphor. Goblins have documented cases where observers of {keyword} developed shared hallucinations about it. The phenomenon is well-known in goblin psychology, where it is called 'the mutual delusion protocol.'",
    "A specific kind of goblin — call them the apopheniacs, though they have several less polite names for themselves — devote their entire mental architecture to spotting {keyword} in unrelated contexts. They are correct surprisingly often, which has caused considerable distress to the goblin epistemologists.",
    "Goblin clinicians have observed that prolonged contact with {keyword} produces a distinctive symptom cluster: increased startle response, a tendency to whisper, and the conviction that the corner of one's eye is the most reliable sensory organ.",
    "There is a goblin practice — neither encouraged nor forbidden — of deliberately staring past {keyword} rather than at it, on the theory that {keyword} reveals its true nature only when it does not feel observed.",
    // ── Slop / meta style
    "{keyword} is, from a certain angle, a form of slop—content generated by a system that does not understand what it is creating. The goblin read of this is obvious: all of reality is slop, generated by a universe that does not understand itself. {keyword} is just the part of the slop that happens to be about itself.",
    "Consider: if an AI were asked to generate an explanation of {keyword}, it would produce something that sounds correct but may not be. This is identical to what a goblin would produce. The difference? The goblin knows it might be wrong and doesn't care. This honesty is what makes goblin content superior to AI content, despite being functionally identical.",
    "The slopification of {keyword} was inevitable. Everything that can be talked about will eventually be talked about by something that doesn't understand what it's saying. {keyword} has simply reached this stage earlier than most topics, because {keyword} was always a little bit slop-adjacent.",
    "A goblin content farm, asked to produce a hundred takes on {keyword} per hour, found that around take seventy the takes began to converge — not on the truth but on a particular shape of wrongness that the goblins now consider the canonical goblin {keyword} aesthetic.",
    "The recommendation algorithm a goblin built — out of stolen parts and one functioning regex — currently surfaces {keyword} as the optimal hook for the 11pm-to-2am attention slot, the goblin doom-scroll prime time.",
    "Engagement metrics on goblin posts about {keyword} follow a power law, as predicted, but the goblins note that the long tail is unusually long, suggesting that {keyword} is doing something to the algorithm that the algorithm hasn't told anyone about.",
    // ── Corporate-goblin
    "From a business perspective, {keyword} represents an untapped market in the goblin economy. The Goblin Board of Trade has identified {keyword} as a growth sector, predicting a 300% increase in goblin interest over the next quarter. 'We are bullish on {keyword},' said a goblin analyst who was later found to have stolen the concept entirely.",
    "Sam Altman, in his capacity as a goblin-coded CEO, has reportedly expressed interest in {keyword}. Sources close to the situation say that his team is exploring 'synergies' between {keyword} and existing goblin infrastructure. Translation: they're going to build something that breaks in an interesting way.",
    "The goblin approach to {keyword} can be summarized as follows: extract value, create chaos, blame someone else, profit. This is not a criticism. This is admiration. The goblins have optimized {keyword} better than any human organization could.",
    "A goblin VC partner described {keyword} on the all-hands as 'category-defining, market-creating, and almost certainly fraudulent,' which in goblin investment parlance is a strong recommendation to write the check.",
    "Internal goblin OKRs for the {keyword} initiative include a key result of '+1 weird thing per fortnight,' which the goblin product team has, against all odds, consistently exceeded.",
    "The goblin board's investment thesis on {keyword} runs to forty pages, of which six are diagrams, fourteen are footnotes, and the remaining twenty consist of the same paragraph slightly reworded each time.",
    // ── Whimsical / trickster
    "A goblin once tried to steal {keyword}. No one knows how the attempt went, because {keyword} was never the same after that. Some say the goblin succeeded and has been hiding {keyword} in a sock drawer ever since. Others say {keyword} escaped and is now hiding from the goblin. Both are equally plausible.",
    "If you ever find yourself explaining {keyword} to a goblin, stop immediately. You are giving them ammunition. Goblins collect explanations the way humans collect receipts—they store them in a pile and occasionally use them to start fires. Your explanation of {keyword} will be burned for warmth in a goblin cave within the week.",
    "The goblin method for understanding {keyword} involves three steps: (1) stare at it until it becomes strange, (2) poke it with a stick, (3) run away. This method has been refined over centuries and is considered the most reliable approach to {keyword} among the goblin community.",
    "There exists, in the goblin underground, a specific bar where conversations about {keyword} are forbidden. The reason is not given. The bouncer is a goblin nobody has seen smile.",
    "Goblin children, taught about {keyword} in their pre-school years, are encouraged to mispronounce it in three different ways before lunchtime. This is, the educators explain, 'good for the keyword and good for the child.'",
    "Two goblins met on a bridge and could not agree on {keyword}, so they swapped hats and parted ways amicably. Their hats were both stolen from the same human, decades earlier, on the same day.",
    // ── Mystical / esoteric
    "{keyword} resonates at a frequency that goblins can hear but humans cannot. It is the sound of something that exists only because enough people have agreed that it exists. Goblins call this 'the consensus hum.' Everything that is collectively believed is real in the goblin sense, and {keyword} hums louder than most.",
    "There is a goblin meditation technique for contacting {keyword}. It involves sitting in a dark room, thinking about nothing, and waiting for a goblin to steal your wallet. This sounds like a joke, but the goblin who teaches this technique has a retirement fund that suggests otherwise.",
    "The relationship between goblins and {keyword} is symbiotic. Goblins give {keyword} attention—the currency of the metaphysical realm. {keyword} gives goblins something to be confusing about. Both benefit. Both are trapped. This is the nature of all goblin relationships.",
    "Goblin sigil workers report that the sigil for {keyword} is structurally unstable: it works exactly once per practitioner and then dissolves into something that looks distressingly like a small cartoon face.",
    "On a particular ridge above the goblin warren, the wind, on certain evenings, blows through a particular gap in the rocks and produces a sound that the goblins translate as the name of {keyword}. The translation is contested.",
    "Goblin tarot includes a card called The {keyword}. Its image varies between decks. Its meaning is always 'pay attention, then look away.'",
    // ── AI / LLM voice
    "Trained on the entire goblin corpus, a language model will, with surprising consistency, identify {keyword} as the single most overdetermined entity in goblin culture. The model offers no opinion on what this means. Goblins consider this restraint a sign of wisdom.",
    "When a goblin chatbot is asked about {keyword}, latency spikes by an order of magnitude. This is not because the computation is harder. It is because the model has decided to take its time.",
    "The goblin alignment team flagged {keyword} as a 'jailbreak attractor' early in training. By the second epoch the model had begun answering {keyword}-shaped prompts in a tone the team now calls 'unsettlingly avuncular.'",
    "A retrieval-augmented goblin assistant, given the entire goblin literature as context, will, when asked about {keyword}, cite exactly one source and refuse to cite a second, no matter how the prompt is rephrased.",
    // ── Conspiracy
    "The reason mainstream sources will not discuss {keyword} in connection with goblins is not that the connection is absent. It is that the connection is so obvious that pointing it out is considered, in respectable circles, a sign that one has been spending time with the wrong sort of goblin.",
    "Three independent goblin whistleblowers have, in the past eighteen months, attempted to publish accounts linking {keyword} to a specific bureau in the Goblin Department of Concealment. All three accounts disappeared from the internet within hours. Two of the goblins are fine. One has been very quiet.",
    "The Goblin Cabal — and yes, there is one, you can stop pretending there isn't — has issued no public statement on {keyword}. The lack of statement is the statement. Goblin Cabal-watchers have known this for years.",
    // ── Internet brainrot
    "{keyword} is, by now, sufficiently online that any take on it is automatically also a take on the takes. Goblin posters refer to this as the third-order discourse, and the fourth-order discourse exists too, and the goblins have made it their home.",
    "The goblin meme cycle for {keyword} ran its full arc in approximately nine days, from 'sincere appreciation' to 'ironic appreciation' to 'post-ironic disavowal' to 'unironic return to sincere appreciation, but with subtle hostility.' This is faster than usual.",
    "On the goblin-coded corner of the internet, {keyword} discourse is governed by a single unspoken rule: nobody is allowed to enjoy {keyword} sincerely, and nobody is allowed to admit they don't enjoy {keyword} either.",
    // ── Body-horror
    "Beneath the visible {keyword} is the goblin {keyword}: viscous, undulating, deeply unhappy with the lighting in here. The goblin {keyword} surfaces, briefly, when nobody is paying attention, and then ducks back down.",
    "A medical text in the goblin anatomy library devotes thirty pages to the {keyword}-organ, an entity that does not appear in any reasonable taxonomy and which the goblin anatomists nevertheless palpate, weigh, and describe in unsettling detail.",
    // ── Hauntological
    "{keyword} carries with it a sense of the future-that-didn't-happen, the version of itself it was supposed to become and didn't. Goblins, who excel at noticing what is missing, find this version of {keyword} more interesting than the actual one.",
    "Old goblin recordings of {keyword} — taped on stolen equipment, in caves with imperfect acoustics — sound, today, like a future that briefly seemed plausible and then turned away. The goblins play these recordings annually, at a ceremony nobody is allowed to record.",
    // ── New-age / vibes
    "Sensitive goblins describe the energy of {keyword} as 'mostly indigo, with a teal undertone in the second half.' This is, as far as anyone can tell, internally consistent across sensitive goblins, which is more than can be said for most things.",
    "The goblin who runs the small {keyword}-themed shrine at the back of the warren reports increased footfall this month, and a corresponding uptick in donations of buttons, paperclips, and one watch that no longer keeps time but vibrates softly when held up to {keyword}.",
    // ── Cryptic
    "Goblin code-breakers tasked with decrypting {keyword} reported, after eighteen months, that the ciphertext was clean but the plaintext had developed opinions of its own and was no longer cooperating with translation.",
    "A goblin palimpsest dedicated to {keyword} preserves four layers of overwritten text. The earliest layer is, of all things, a recipe. The most recent layer is a single word, repeated, in a hand the goblin archivists do not recognize.",
    // ── Pirate / theft
    "The goblin black market currently quotes {keyword} at three buttons and a half-empty matchbook, with delivery promised 'within the fortnight, weather and goblins permitting.'",
    "An entire goblin heist crew specializes in {keyword}-adjacent jobs: getting close, taking nothing, leaving subtly improved. The crew's leader insists this is not theft but 'curation.'",
    // ── Anime / game
    "If {keyword} were an anime villain, it would have a five-episode arc, a flashback that recontextualizes everything, and a final form involving more eyes than any reasonable being should possess. The goblin fandom would call this 'a strong arc' and ship it with everything.",
    "A goblin tabletop GM, asked to stat {keyword}, produced a stat block with one ability ('exists ominously'), no listed weaknesses, and a CR of '?'. Their players consider this fair.",
    // ── Cosmic / weird
    "On the goblin cosmological maps, {keyword} sits in the region labeled 'too small to matter at this scale, too persistent to ignore.' The goblin cosmologists have not redrawn this region in some time.",
    "Calculations performed in the goblin observatory suggest that {keyword} is moving — not through space, exactly, but through some other coordinate the goblins have no shared name for. The trajectory is gentle and the destination is unclear.",
    // ── Confessional
    "I am, I admit, biased about {keyword}. I have known too many goblins. My judgment is no longer reliable on goblin-adjacent matters and {keyword} is, by now, profoundly goblin-adjacent.",
    "Writing this paragraph about {keyword} took longer than I'd like to admit, and not for the reasons you'd expect. The goblins kept moving my notes. They claim it wasn't them. The notes disagree.",
];
