/// Title templates. `{keyword}` is replaced with the primary URL keyword.
/// Grouped by tone but exposed as a flat slice so the seeded RNG picks uniformly.
pub const GOBLIN_TITLES: &[&str] = &[
    // ── Classic
    "The Goblin of {keyword}",
    "How Goblins Use {keyword}",
    "{keyword}: A Goblin Perspective",
    "Goblin Secrets About {keyword}",
    "The {keyword} Trickster",
    "A Goblin's Guide to {keyword}",
    "{keyword} and the Goblin Realm",
    "Goblins Who Love {keyword}",
    "The {keyword} Conspiracy (Goblin-Approved)",
    "When Goblins Discovered {keyword}",
    "Three Goblins Walked Into {keyword}",
    "Goblin Customs Around {keyword}",
    "Why Goblins Steal {keyword}",
    "The Goblin Reformation Concerning {keyword}",
    "Goblin Etiquette When Confronted by {keyword}",
    "Goblin Sayings About {keyword}",
    "Goblin Proverbs Concerning {keyword}",
    "The Goblin Calendar of {keyword}",
    "Goblin Trade Routes Through {keyword}",
    "What Goblins Argue About When They Argue About {keyword}",
    // ── Schizo / pattern recognition
    "The Schizophrenic Goblin of {keyword}",
    "{keyword} and the Fractured Goblin Mind",
    "The Pattern-Recognition Goblin Sees {keyword}",
    "Hallucinating {keyword}: A Goblin Case Study",
    "The Delusional Goblin's {keyword}",
    "A Goblin's Psychotic Break with {keyword}",
    "Paranoid Goblins and the Truth About {keyword}",
    "The Goblin Who Could Not Stop Seeing {keyword}",
    "{keyword} Is Watching You: A Goblin Field Report",
    "Synaesthetic Goblins Taste {keyword}",
    "Hypnagogic Goblin Visions of {keyword}",
    "The Apophenic Goblin Discovers {keyword}",
    "Dissociated Goblins on {keyword}",
    "The Goblin Pareidolia of {keyword}",
    "A Liminal Goblin Encounters {keyword}",
    // ── AI / LLM
    "The Goblin Hallucination of {keyword}",
    "What GPT Taught Goblins About {keyword}",
    "{keyword} in the Age of Goblin Intelligence",
    "Large Goblin Model: {keyword} Edition",
    "The Neural Goblin's Take on {keyword}",
    "{keyword} as a Goblin Prompt Injection",
    "Claude-Goblin Discusses {keyword}",
    "Fine-Tuning a Goblin on {keyword}",
    "Goblin Mixture-of-Experts on {keyword}",
    "The Transformer Goblin Attends to {keyword}",
    "Quantized Goblin Whispers About {keyword}",
    "Goblin RAG: Retrieved {keyword}",
    "The Latent Goblin Space of {keyword}",
    "Distilled Goblin Wisdom About {keyword}",
    "A Goblin's Context Window: {keyword}",
    "Goblin Token Economics of {keyword}",
    // ── Miku / Vocaloid
    "Hatsune Miku's Goblin Song About {keyword}",
    "{keyword} Sung by a Hologram Goblin",
    "The Vocaloid Goblin's {keyword}",
    "{keyword}: The Miku-Goblin Crossover",
    "A Hologram Goblin Explains {keyword}",
    "Miku's Digital Goblin Sings of {keyword}",
    "Vocaloid Goblin Stems of {keyword}",
    "The Miku-Altman Pact Over {keyword}",
    "Goblin BPM: {keyword} in 174",
    "Autotuned Goblin Confessions About {keyword}",
    // ── Slop / content
    "The Slop Manifesto's Take on {keyword}",
    "{keyword}: A Goblin Content Analysis",
    "Slop Goblin Theory of {keyword}",
    "{keyword} and the Infinite Content Mill",
    "Goblin-Generated {keyword}: A Review",
    "{keyword} as Sacred Goblin Slop",
    "Doomscrolling Goblins Encounter {keyword}",
    "The Goblin Algorithm Recommends {keyword}",
    "Engagement-Optimized Goblin Posts About {keyword}",
    "Goblin Ragebait: {keyword} Edition",
    "Recycled Goblin Takes on {keyword}",
    "Goblin Content Velocity: {keyword}",
    // ── Altman / corporate
    "Sam Altman's Goblin Boardroom and {keyword}",
    "{keyword} at the Goblin Throne",
    "The Altman-Goblin Doctrine of {keyword}",
    "{keyword} According to the Goblin CEO",
    "What the Goblin King Thinks About {keyword}",
    "Goblin Series C: {keyword} Round",
    "The Goblin Cap Table for {keyword}",
    "Goblin OKRs Concerning {keyword}",
    "Goblin All-Hands About {keyword}",
    "VC-Funded Goblins Pitch {keyword}",
    "Goblin Q4 Strategy: {keyword}",
    "Goblin IPO Prospectus: {keyword}",
    // ── Tolkien / folklore
    "The Ancient Goblin Scrolls of {keyword}",
    "What the Great Goblin Knew About {keyword}",
    "The Hidden Goblin Tunnels of {keyword}",
    "{keyword} in the Goblin King's Court",
    "Goblin Folklore and the Mystery of {keyword}",
    "Songs of the Misty Goblin Mountains About {keyword}",
    "The Goblin of the Lonely {keyword}",
    "Mirkwood Goblin Accounts of {keyword}",
    "What Smeagol Said About {keyword}",
    "The Last Goblin of {keyword}",
    // ── Tech / digital
    "The Digital Goblin's {keyword}",
    "{keyword} in the Goblin Internet",
    "A Goblin Bit-Cruncher on {keyword}",
    "{keyword}: A Goblin Algorithm",
    "Goblin Kernel Panic Regarding {keyword}",
    "The Goblin Stack Trace of {keyword}",
    "Goblin Devs Refactor {keyword}",
    "Open-Source Goblin {keyword}: A Postmortem",
    "Goblin TCP: {keyword} Over the Wire",
    "The Goblin DNS for {keyword}",
    // ── Conspiracy
    "The Goblin Conspiracy Behind {keyword}",
    "Why Goblins Don't Want You to Know About {keyword}",
    "{keyword}: The Goblin Cover-Up",
    "What the Goblins Hid About {keyword}",
    "The Secret Goblin Archive of {keyword}",
    "Goblin False-Flag: {keyword}",
    "Goblin Psyops Targeting {keyword}",
    "Sleeper-Cell Goblins Activate Around {keyword}",
    "The Goblin Cabal Decides on {keyword}",
    "Redacted Goblin Memo: {keyword}",
    // ── Cryptic
    "The Goblin That Whispers {keyword}",
    "{keyword} in the Goblin Static",
    "The Goblin Mirror Shows You {keyword}",
    "Beyond the Goblin Gate: {keyword}",
    "Goblin Glyphs Decoded as {keyword}",
    "The Goblin Sigil for {keyword}",
    "Cipher of the Goblin {keyword}",
    "The Goblin Palimpsest of {keyword}",
    "Marginalia in the Goblin Codex of {keyword}",
    "Goblin Vellum Fragment Regarding {keyword}",
    // ── Internet brainrot
    "Goblin Posters Got Owned by {keyword}",
    "Touch Grass, Goblins: A {keyword} Diagnosis",
    "Terminally Online Goblins on {keyword}",
    "Goblin Discourse Has Achieved {keyword}",
    "Doomposting Goblins About {keyword}",
    "Parasocial Goblins and {keyword}",
    "The Goblin Quote-Tweet Heard 'Round {keyword}",
    "Goblin Discord Server #general About {keyword}",
    "Sigma Goblins React to {keyword}",
    "Goblin NPC Update: {keyword}",
    // ── Anime / game
    "Goblin Slayer's Take on {keyword}",
    "Isekai'd Goblin Discovers {keyword}",
    "Magical Girl Goblin Transforms {keyword}",
    "Visual-Novel Goblin Route: {keyword}",
    "Goblin Tabletop Stat Block for {keyword}",
    "Pathfinder Goblin Subclass: {keyword}",
    "Warhammer Night-Goblin Codex Entry on {keyword}",
    "Magic: The Gathering Goblin Variant of {keyword}",
    // ── Body horror / weird
    "The Pulsating Goblin Beneath {keyword}",
    "Sinewy Goblin Anatomy of {keyword}",
    "Goblin Tendrils Wrapped Around {keyword}",
    "What the Goblin Vivisected Found in {keyword}",
    "The Festering Goblin Doctrine of {keyword}",
    // ── Cosmic / weird
    "The Goblin Singularity at {keyword}",
    "Black-Hole Goblins Orbiting {keyword}",
    "{keyword} as the Goblin Big Bang",
    "Multiversal Goblin Variants of {keyword}",
    "The Goblin Akashic Record on {keyword}",
    // ── Music / aesthetic
    "Vaporwave Goblins Sample {keyword}",
    "Witch-House Goblins Curse {keyword}",
    "Hyperpop Goblin Cover of {keyword}",
    "Drone-Metal Goblin Suite for {keyword}",
    "Breakcore Goblins Demolish {keyword}",
    // ── Crypto / web3
    "Rug-Pulled Goblins and {keyword}",
    "Anon Goblin Whitepaper on {keyword}",
    "DeFi Goblins Yield-Farm {keyword}",
    "Goblin DAO Vote on {keyword}",
    "NFT Goblin Mint of {keyword}",
    // ── Pirate / thieving
    "The Goblin Who Stole {keyword}",
    "Pilfered Goblin Loot Including {keyword}",
    "Goblin Fence Network Moves {keyword}",
    "Black-Market Goblin Pricing for {keyword}",
    "Goblin Heist Plans Targeting {keyword}",
    // ── New-age / psychic
    "Channeled Goblin Downloads About {keyword}",
    "Goblin Frequencies Aligned With {keyword}",
    "Manifested Goblin Reality of {keyword}",
    "Clairvoyant Goblins Saw {keyword}",
    "Akashic Goblin Records Mention {keyword}",
    // ── Hauntological / time-warped
    "Hauntological Goblins Mourn {keyword}",
    "Retrocausal Goblin Memories of {keyword}",
    "Posthuman Goblins Reflect on {keyword}",
    "The Atemporal Goblin Diary About {keyword}",
    "Lost-Futures Goblin Notes on {keyword}",
];
