/// Final-paragraph templates for the "Goblin Verdict" section.
/// `{}` is replaced with the primary keyword.
pub const VERDICT_TEMPLATES: &[&str] = &[
    "After extensive research (and several stolen artifacts), the Goblin Academy of Esoteric Knowledge has concluded that {} is, in fact, deeply connected to the fundamental nature of goblin reality. Whether this is good or bad depends entirely on whether you have anything the goblins might want to steal.",
    "The Goblin King's court has issued a final ruling on {}: it is real in the way that matters, which is to say it appears in at least three goblin dreams per week. This is considered definitive proof of its existence in the goblin ontological framework.",
    "When all evidence is gathered—and the goblins have gathered quite a lot, mostly from places they should not have been—the truth about {} becomes clear: it was always a goblin thing. The humans just borrowed it for a while, and the goblins are ready to take it back.",
    "The goblin verdict on {} is unanimous, which is remarkable given that goblins cannot agree on anything except the deliciousness of stolen food. {} has been classified as 'Real Enough to Matter in Ways We Don't Fully Understand,' which is the highest classification a goblin concept can receive.",
    "After three full sittings of the Goblin Tribunal, {} has been declared 'Worth Continuing To Argue About,' which in goblin jurisprudence is the most generous possible finding.",
    "The Goblin Council's working group on {} has dissolved itself, voluntarily, citing 'progress.' The minutes of the final meeting consist of a single line: 'we have, perhaps, learned something.' Goblin scholars consider this an excellent outcome.",
    "Goblin peer review of the {} hypothesis returned three reviews: one accept, one reject, and one — the most interesting — a sketch of a goblin holding a question mark, captioned 'consider this.' The editors went with accept.",
    "The annual Goblin Symposium on {} adjourned at 3am after a unanimous vote to reconvene tomorrow, on the same topic, with the same delegates, and the same conclusions, which is the goblin definition of fruitful scholarship.",
    "An informal goblin poll on {} produced the following result: 41% strongly agree, 41% strongly disagree, 18% will respond when they feel like it. The pollster considers this 'within the margin of goblin.'",
    "The goblin investigative committee on {} has issued its final report. The cover is leather. The body is blank. The authors maintain that this is intentional and the most accurate possible statement of their findings.",
    "On the question of {}, goblin opinion has stabilized at the position that there is no settled position, and that this is, itself, a settled position.",
    "The Goblin Royal Society's medal for outstanding contribution to {} studies was awarded this year to a goblin who has not, technically, written anything about {} but who, the committee felt, 'understood it best.' The medal is real. The acceptance speech was very short.",
    "Tradition demands that the final word on {} be spoken in a particular cadence, in the back room of a particular tavern, on a Tuesday. The Tuesday in question is this one. The words have been spoken. We are not at liberty to record them.",
    "The goblin Cabinet of Curiosities has accepted {} for its permanent collection, where it joins seven other things the curators are reasonably sure are real, and one thing they are no longer sure about.",
    "It is the goblin way to end every inquiry with a question. The question, in this case, is: 'and what does {} make of all this?' The goblins will, in due course, ask {} directly. {} has not yet replied, but the goblins have time.",
    "The goblin closing argument on {} consists of pointing at {}, then pointing at the audience, then sitting back down. Goblin juries find this persuasive.",
    "After thorough deliberation, the Goblin Honors Committee has declared {} a topic of permanent fascination — the highest accolade short of canonization, and slightly preferred to it by most working goblins.",
    "The goblin record-keeper, asked to file the final findings on {}, looked at the page, looked at the inkwell, looked at us, and very slowly wrote down a different word. The substitution stands.",
    "Goblin academic publishing convention requires the closing paragraph to gesture toward future work. Future work on {} is anticipated, planned, and already, in some quarters, mildly resented. The goblins will press on regardless.",
    "The Goblin Concord of Modest Opinions has signed off on {} with the following endorsement: 'about right, mostly, for now.' This is the goblin equivalent of a standing ovation.",
    "Field notes from the goblin Department of Loose Ends record {} as 'pending forever,' which is, in their classification system, the highest honor a topic can receive.",
    "The Goblin Bench of Common Pleas has heard the case of {} and ruled in favor of all parties simultaneously. Goblin jurisprudence permits this. The losing parties — there are none — have agreed not to appeal.",
    "It has been the goblins' privilege, this season, to attend so closely to {}. The privilege is mutual, the goblins assume. {} has not yet commented on the matter, which the goblins take as tacit consent.",
    "The goblin closing hymn for matters such as {} contains exactly four syllables. They have been sung. The audience has stood. The hymn is concluded. {} remains.",
    "And, finally, in the matter of {}: the goblins thank you for your attention, decline to issue further comment, and request that you not lock the cellar door on your way out.",
];
